accounts/urls.py
from django.urls import path

from . import views


app_name = "accounts"
urlpatterns = [
    path('signin', views.signin, name='signin'),
    path('signup', views.signup, name='signup'),
    path('signout', views.signout, name='signout'),
    path('perfil/alterar', views.user_profile_update, name='user_profile_update'),
    path('senha/alterar', views.update_password, name='update_password'),
]

django_weight_recorde/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("weight_recorder.urls", namespace="weight_recorder")),
    path("conta/", include("accounts.urls", namespace="accounts")),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

weight_recorder/urls.py
from django.urls import path

from . import views


app_name = "weight_recorder"
urlpatterns = [
    path("dashboard", views.dashboard, name="dashboard"),
    path("peso/adicionar", views.weight_create, name="weight_create"),
    path("peso/<int:pk>/editar", views.weight_edit, name="weight_edit"),
    path("peso/<int:pk>/apagar", views.weight_delete, name="weight_delete"),
]

accounts/models.py
from django.db import models

from weight_recorder.models import Weight


class UserProfile(models.Model):
    profile_image = models.ImageField(
        verbose_name="Foto de perfil", default="default.png", upload_to="profile_image/%d/%m/%Y", blank=False, null=False)
    height = models.FloatField("Altura", blank=True, null=True)
    weight_goal = models.FloatField("Meta de peso", blank=True, null=True)
    user = models.OneToOneField(
        "auth.User", verbose_name="Usuário", on_delete=models.CASCADE, blank=False, null=False)

    def get_imc(self):
        if not self.height:
            return 0
        weights = Weight.objects.filter(insert_by=self.user)
        weight = weights.latest('weight_date')
        return weight.weight_value / self.height ** 2

weight_recorder/models.py
from django.db import models


class Weight(models.Model):
    weight_value = models.FloatField(verbose_name="Peso", blank=False)
    weight_date = models.DateField(
        "Data do registro", blank=False)
    created_at = models.DateTimeField(
        verbose_name="Data de criação", auto_now=False, auto_now_add=True)
    insert_by = models.ForeignKey(
        "auth.User", verbose_name="Usuário", on_delete=models.CASCADE, blank=False)

    class Meta:
        verbose_name = "Peso"
        ordering = ("weight_date",)

    def __str__(self):
        return f"{self.insert_by.username} ({self.weight_value}Kg)"

accounts/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import UserProfile


class SignInForm(forms.Form):
    username = forms.CharField(label='Nome de usuário', required=True)
    password = forms.CharField(
        label='Senha', required=True, widget=forms.PasswordInput)


class SignUpForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'password')


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        exclude = ('user',)


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')

weight_recorder/forms.py
from django import forms

from .models import Weight


class WeightForm(forms.ModelForm):
    class Meta:
        model = Weight
        fields = ('weight_value', 'weight_date')

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib import messages

from .forms import SignInForm, SignUpForm, UserProfileForm, UserUpdateForm
from .models import UserProfile


def signin(request):
    if request.method == 'POST':
        form = SignInForm(request.POST)

        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)

            if user is not None:
                login(request, user)
                return redirect('weight_recorder:dashboard')

    form = SignInForm()
    context = {
        'title': 'Sign In',
        'form': form,
    }

    return render(request, 'accounts/signin.html', context)


def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)

        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(user.password)
            user.save()
            UserProfile.objects.create(user=user)
            return redirect('accounts:signin')

    form = SignUpForm()
    context = {
        'title': 'Sign Un',
        'form': form,
    }

    return render(request, 'accounts/signup.html', context)


@login_required
def signout(request):
    logout(request)
    return redirect('accounts:signin')


@login_required
def user_profile_update(request):
    user_profile = request.user.userprofile

    if request.method == 'POST':
        user_form = UserUpdateForm(request.POST, instance=request.user)
        user_profile_form = UserProfileForm(
            request.POST, request.FILES, instance=user_profile)

        if user_form.is_valid() and user_profile_form.is_valid():
            user_form.save()
            user_profile_form.save()
            messages.success(request, 'Perfil atualizado com sucesso')

            return redirect('weight_recorder:dashboard')

    user_form = UserUpdateForm(instance=request.user)
    user_profile_form = UserProfileForm(instance=user_profile)
    context = {
        'title': 'Atualizar Perfil',
        'user_profile_form': user_profile_form,
        'user_form': user_form,
    }

    return render(request, 'accounts/user_profile_form.html', context)


@login_required
def update_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(user=request.user, data=request.POST)

        if form.is_valid():
            form.save()
            messages.success(request, 'Senha alterada com sucesso')
            update_session_auth_hash(request, form.user)

            return redirect('weight_recorder:dashboard')

    form = PasswordChangeForm(user=request.user)
    context = {
        'title': 'Alterar Senha',
        'form': form,
    }

    return render(request, 'accounts/update_password.html', context)

weight_recorder/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from .models import Weight
from .forms import WeightForm


@login_required
def dashboard(request):
    weight_list = Weight.objects.filter(insert_by=request.user)
    weight_chart_data = {
        'labels': [weight.weight_date.strftime('%d/%m/%Y') for weight in weight_list],
        'data': [weight.weight_value for weight in weight_list]
    }

    context = {
        'title': 'Dashboard',
        'weight_list': weight_list,
        'weight_chart_data': weight_chart_data,
    }

    return render(request, 'weight_recorder/dashboard.html', context)


@login_required
def weight_create(request):
    if request.method == 'POST':
        form = WeightForm(request.POST)

        if form.is_valid():
            weight = form.save(commit=False)
            weight.insert_by = request.user
            weight.save()
            messages.success(request, 'Peso cadastrado com sucesso')

            return redirect('weight_recorder:dashboard')

    form = WeightForm()
    context = {
        'title': 'Adicionar novo peso',
        'form': form,
    }

    return render(request, 'weight_recorder/weight_form.html', context)


@login_required
def weight_edit(request, pk):
    weight = get_object_or_404(Weight, pk=pk, insert_by=request.user)

    if request.method == 'POST':
        form = WeightForm(request.POST, instance=weight)

        if form.is_valid():
            form.save()
            messages.success(request, 'Peso modificado com sucesso')

            return redirect('weight_recorder:dashboard')

    form = WeightForm(instance=weight)
    context = {
        'title': 'Editar peso',
        'form': form,
    }

    return render(request, 'weight_recorder/weight_form.html', context)


@login_required
def weight_delete(request, pk):
    weight = get_object_or_404(Weight, pk=pk, insert_by=request.user)
    weight.delete()
    messages.success(request, 'Peso deletado com sucesso')

    return redirect('weight_recorder:dashboard')

accounts/templates/accounts/signin.html
{% extends 'scaffold.html' %}

{% load static %}

{% load widget_tweaks %}

{% block scaffold_styles %}
    <link type="text/css" rel="stylesheet" href="{% static 'accounts/css/style.css' %}" media="screen,projection" />
{% endblock scaffold_styles %}

{% block title %}
    {{ title }}
{% endblock title %}

{% block body %}
    <main class="container">
        <div id="login-page" class="row">
            <div class="col s12 z-depth-6 card-panel">
                <form method="POST" class="login-form">
                    {% csrf_token %}
                    <div class="row">
                    </div>
                    <div class="row">
                        <div class="input-field col s12">
                            <i class="material-icons prefix">person_outline</i>
                            {{ form.username|add_class:"validate" }}
                            <label for="{{ form.username.id_for_label }}">Nome de Usuário</label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field col s12">
                            <i class="material-icons prefix">lock_outline</i>
                            {{ form.password }}
                            <label for="{{ form.password.id_for_label }}">Senha</label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field col s12">
                            <button type="submit" class="btn waves-effect waves-light col s12">Sign In</button>
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field col s6 m6 l6">
                            <p class="margin medium-small"><a href="{% url 'accounts:signup' %}">Criar nova conta!</a></p>
                        </div>
                    </div>

                </form>
            </div>
        </main>
{% endblock body %}

accounts/templates/accounts/signup.html
{% extends 'scaffold.html' %}

{% load static %}

{% load widget_tweaks %}

{% block scaffold_styles %}
    <link type="text/css" rel="stylesheet" href="{% static 'accounts/css/style.css' %}" media="screen,projection" />
{% endblock scaffold_styles %}

{% block title %}
    {{ title }}
{% endblock title %}

{% block body %}
    <main class="container">
        <div id="login-page" class="row">
            <div class="col s12 z-depth-6 card-panel">
                <form method="POST" class="login-form">
                    {% csrf_token %}
                    <div class="row">
                        <div class="input-field col s12 l6">
                            <i class="material-icons prefix">edit</i>
                            {{ form.first_name|add_class:"validate" }}
                            <label for="{{ form.first_name.id_for_label }}">Nome</label>
                        </div>
                        <div class="input-field col s12 l6">
                            <i class="material-icons prefix">edit</i>
                            {{ form.last_name|add_class:"validate" }}
                            <label for="{{ form.last_name.id_for_label }}">Sobrenome</label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field col s12">
                            <i class="material-icons prefix">person_outline</i>
                            {{ form.username|add_class:"validate" }}
                            <label for="{{ form.username.id_for_label }}">Nome de Usuário</label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field col s12">
                            <i class="material-icons prefix">mail_outline</i>
                            {{ form.email|add_class:"validate" }}
                            <label for="{{ form.email.id_for_label }}">E-mail</label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field col s12">
                            <i class="material-icons prefix">lock_outline</i>
                            {{ form.password|attr:"type:password" }}
                            <label for="{{ form.password.id_for_label }}">Senha</label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field col s12">
                            <button type="submit" class="btn waves-effect waves-light col s12">Sign Up</button>
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field col s6 m6 l6">
                            <p class="margin medium-small"><a href="{% url 'accounts:signin' %}">Já possui uma conta?</a></p>
                        </div>
                    </div>

                </form>
            </div>
        </main>
{% endblock body %}

accounts/templates/accounts/update_password.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block content %}

    <main class="container">
        <div class="row">
            <div class="col 12">
                <h2>{{ title }}</h2>
                <div class="divider"></div>
            </div>
        </div>

        <div class="row">
            <form class="col s12" method="POST">
                {% csrf_token %}
                <div class="row">
                    <div class="input-field col s12">
                        <i class="material-icons prefix">lock_outline</i>
                        {{ form.old_password|attr:"type:password" }}
                        <label for="{{ form.old_password.id_for_label }}">Senha anterior</label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s12">
                        <i class="material-icons prefix">lock_outline</i>
                        {{ form.new_password1|attr:"type:password" }}
                        <label for="{{ form.new_password1.id_for_label }}">Nova senha</label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s12">
                        <i class="material-icons prefix">lock_outline</i>
                        {{ form.new_password2|attr:"type:password" }}
                        <label for="{{ form.new_password2.id_for_label }}">Comfirma nova senha</label>
                    </div>
                </div>

                <button type="submit" class="btn btn-primary">Salvar</button>
            </form>
        </div>
    </main>

{% endblock content %}

accounts/templates/accounts/user_profile_form.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block content %}
    <main class="container">
        <div class="row">
            <div class="col s12">
                <h2>{{title}}</h2>
                <div class="divider"></div>
            </div>
        </div>

        <div class="row">
            <div class="col s12 l6">
                <img src="{{ user.userprofile.profile_image.url }}" id="profile_image" class="responsive-img">
            </div>
            <form method="POST" enctype="multipart/form-data" class="col s12 l6">
                {% csrf_token %}
                <div class="row">
                    <div class="input-field col s12 l6">
                        <i class="material-icons prefix">edit</i>
                        {{ user_form.first_name|add_class:"validate" }}
                        <label for="{{ user_form.first_name.id_for_label }}">Nome</label>
                    </div>
                    <div class="input-field col s12 l6">
                        <i class="material-icons prefix">edit</i>
                        {{ user_form.last_name|add_class:"validate" }}
                        <label for="{{ user_form.last_name.id_for_label }}">Sobrenome</label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s12">
                        <i class="material-icons prefix">mail_outline</i>
                        {{ user_form.email|add_class:"validate" }}
                        <label for="{{ user_form.email.id_for_label }}">E-mail</label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s12 l6">
                        <i class="material-icons prefix">straighten</i>
                        {{ user_profile_form.height|add_class:"validate" }}
                        <label for="{{ user_profile_form.height.id_for_label }}">Altura</label>
                    </div>
                    <div class="input-field col s12 l6">
                        <i class="material-icons prefix">mode_edit</i>
                        {{ user_profile_form.weight_goal|add_class:"validate" }}
                        <label for="{{ user_profile_form.weight_goal.id_for_label }}">Objetivo de peso</label>
                    </div>
                </div>
                <div class="row">
                    <div class="file-field input-field col s12">
                        <div class="btn">
                            <span>{{ user_profile_form.profile_image.label }}</span>
                            <input onchange="document.getElementById('profile_image').src = window.URL.createObjectURL(this.files[0])" type="file" accept="image/*" id="{{ user_profile_form.profile_image.id_for_label }}" name="{{ user_profile_form.profile_image.html_name }}">
                        </div>
                        <div class="file-path-wrapper">
                            <input class="file-path validate" type="text">
                            <span class="helper-text">Atualmente: <a target="_blank" href="{{ user.userprofile.profile_image.url }}">{{ user.userprofile.profile_image.url }}</a></span>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col s12">
                        <button class="btn waves-effect waves-light green lighten-1" type="submit" name="action">
                            Salvar <i class="material-icons right">send</i>
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </main>
{% endblock content %}

templates/base.html
{% extends 'scaffold.html' %}

{% load static %}

{% block scaffold_styles %}
    <style>
        .logo-img {
            max-height: 100px!important;
            padding: 5px 0!important;
        }
    </style>
    <link type="text/css" rel="stylesheet" href="{% static 'css/style.css' %}"  media="screen,projection"/>
    {% block styles %}{% endblock styles %}
{% endblock scaffold_styles %}

{% block body %}
    <nav>
        <div class="nav-wrapper">
            <a href="{% url 'weight_recorder:dashboard' %}" class="brand-logo">Weight Recorder</a>
            <a href="#" data-target="slide-out" class="sidenav-trigger"><i class="material-icons">menu</i></a>
            <ul id="nav-mobile" class="right hide-on-med-and-down">
                <li>
                    <a class="dropdown-trigger" href="#!" data-target="user-dropdown">
                        {{ user.get_full_name|default:user.username }}<i class="material-icons right">arrow_drop_down</i>
                    </a>
                </li>
            </ul>
        </div>
    </nav>

    <ul id="slide-out" class="sidenav">
        <li>
            <div class="user-view">
                <div class="background">
                    <img src="https://materializecss.com/images/office.jpg">
                </div>
                <img class="circle" src="{{ user.userprofile.profile_image.url }}">
                <span class="white-text name">{{ user.get_full_name }}</span>
                <span class="white-text email">{{ user.email }}</span>
            </div>
        </li>
        <li><a href="{% url 'weight_recorder:dashboard' %}">Dashboard</a></li>
        <li><a href="{% url 'accounts:user_profile_update' %}">Atualizar Perfil</a></li>
        <li class="divider"></li>
        <li><a href="{% url 'accounts:update_password' %}">Alterar Senha</a></li>
        <li><a href="{% url 'accounts:signout' %}">Sign Out</a></li>
    </ul>

    <!-- User Dropdown Structure -->
    <ul id="user-dropdown" class="dropdown-content">
        <li>
            <div style="width:100%" class="center"><img src="{{ user.userprofile.profile_image.url }}" alt="" class="logo-img circle responsive-img"></div>
            <div style="width:100%" class="center">
                <div class="chip">
                    IMC: {{ user.userprofile.get_imc|floatformat:2 }}
                </div>
            </div>
        </li>
        <li><a href="{% url 'accounts:user_profile_update' %}">Atualizar Perfil</a></li>
        <li class="divider"></li>
        <li><a href="{% url 'accounts:update_password' %}">Alterar Senha</a></li>
        <li><a href="{% url 'accounts:signout' %}">Sign Out</a></li>
    </ul>

    {% block content %}
    {% endblock content %}

    <footer class="page-footer">
        <div class="container">
            <div class="row">
                <div class="col l6 s12">
                    <h5 class="white-text">Footer Content</h5>
                    <p class="grey-text text-lighten-4">You can use rows and columns here to organize your footer content.</p>
                </div>
                <div class="col l4 offset-l2 s12">
                    <h5 class="white-text">Links</h5>
                    <ul>
                        <li><a class="grey-text text-lighten-3" href="#!">Link 1</a></li>
                        <li><a class="grey-text text-lighten-3" href="#!">Link 2</a></li>
                        <li><a class="grey-text text-lighten-3" href="#!">Link 3</a></li>
                        <li><a class="grey-text text-lighten-3" href="#!">Link 4</a></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="footer-copyright">
            <div class="container">
                © 2014 Copyright Text
                <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
            </div>
        </div>
    </footer>
{% endblock body %}

{% block scaffold_scripts %}
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            var elems = document.querySelectorAll('.dropdown-trigger');
            var instances = M.Dropdown.init(elems);
        });

        document.addEventListener('DOMContentLoaded', function() {
            var elems = document.querySelectorAll('.sidenav');
            var instances = M.Sidenav.init(elems);
        });
    </script>
    {% include 'partials/_messages.html' %}

    {% block scripts %}{% endblock scripts %}
{% endblock scaffold_scripts %}

templates/partials/_messages.html
<script>
    {% if messages %}
        {% for message in messages %}
            M.toast({html: '{{ message }}'})
        {% endfor %}
    {% endif %}
</script>

templates/scaffold.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!--Import materialize.css-->
    <link type="text/css" rel="stylesheet" href="{% static 'css/materialize.min.css' %}" media="screen,projection" />

    {% block  scaffold_styles %}{% endblock scaffold_styles %}

    <title>
        {% block title %}{% endblock title %} - Weight Recorder
    </title>
</head>

<body>
    {% block body %}{% endblock body %}

    <!--JavaScript at end of body for optimized loading-->
    <script type="text/javascript" src="{% static 'js/materialize.min.js' %}"></script>
    {% block scaffold_scripts %}{% endblock scaffold_scripts %}
</body>

</html>

weight_recorder/templates/weight_recorder/dashboard.html
{% extends 'base.html' %}
{% load static %}
{% load l10n %}

{% block title %}
    {{ title }}
{% endblock title %}

{% block content %}

    <main class="container">
        <div class="row">
            <div class="col s12">
                <h2>{{ title }}</h2>
                <div class="divider"></div>
            </div>
        </div>

        {% if weight_list %}
            <div class="row">
                <div class="col s12 l6">
                    <canvas id="weight-chart"></canvas>
                </div>

                <div class="col s12 l6">
                    <table class="striped">
                        <thead>
                            <tr>
                                <th>Peso</th>
                                <th>Data</th>
                                <th>Ações</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for weight in weight_list %}
                                <tr>
                                    <td>{{ weight.weight_value }} Kg</td>
                                    <td>{{ weight.weight_date }}</td>
                                    <td>
                                        <a href="{% url 'weight_recorder:weight_edit' pk=weight.pk %}" class="tooltipped waves-effect waves-light btn blue lighten-1" data-position="top" data-tooltip="Editar">
                                            <i class="material-icons">edit</i>
                                        </a>
                                        <a href="{% url 'weight_recorder:weight_delete' pk=weight.pk %}" onclick="return confirm('Certeza que deseja remover este peso?');" class="tooltipped waves-effect waves-light btn red lighten-1" data-position="top" data-tooltip="Apagar">
                                            <i class="material-icons">delete</i>
                                        </a>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        {% else %}
            <div class="tap-target blue lighten-1" data-target="add_weight_btn">
                <div class="tap-target-content">
                    <h5>Nenhum peso cadastrado</h5>
                    <p>
                        Você ainda não registrou nenhuma pessagem no sistema, clique no botão <i class="material-icons">add</i> para registrar uma nova pesagem.
                    </p>
                </div>
            </div>
        {% endif %}

        <div class="fixed-action-btn">
            <a href="{% url 'weight_recorder:weight_create' %}" id="add_weight_btn" class="btn-floating btn-large waves-effect waves-light green lighten-1">
                <i class="material-icons">add</i>
            </a>
        </div>
    </main>
{% endblock content %}

{% block scripts %}
    <script type="text/javascript" src="{% static 'js/chart.min.js' %}"></script>
    <script>
        {% if weight_list %}
            var ctx = document.getElementById('weight-chart').getContext('2d');
            var chart = new Chart(ctx, {
                // The type of chart we want to create
                type: 'line',

                // The data for our dataset
                data: {
                    labels: {{ weight_chart_data.labels|safe }},
                    datasets: [{
                        label: 'Peso',
                        fill: false,
                        borderColor: 'rgb(255, 99, 132)',
                        lineTension: 0,
                        data: {{ weight_chart_data.data|safe }}
                    }, {
                        label: 'Meta',
                        fill: false,
                        borderColor: 'rgb(66,165,245)',
                        data: [{% for data in weight_chart_data.data %}{{ user.userprofile.weight_goal|unlocalize }},{% endfor %}],
                        type: 'line',
                        // this dataset is drawn on top
                        order: 2
                    }]
                },

                // Configuration options go here
                options: {}
            });
        {% endif %}

        document.addEventListener('DOMContentLoaded', function() {
            var elems = document.querySelectorAll('.tooltipped');
            var instances = M.Tooltip.init(elems);
        });

        {%if not weight_list %}
            document.addEventListener('DOMContentLoaded', function() {
                var elems = document.querySelectorAll('.tap-target');
                var instances = M.TapTarget.init(elems);
                instances[0].open();
            });
        {% endif %}
    </script>
{% endblock scripts %}